<Project>
  <PropertyGroup>
    <Version>1.5.0</Version>
    <AssemblyVersion>$(Version).0</AssemblyVersion>
    <IncludeSourceRevisionInInformationalVersion>true</IncludeSourceRevisionInInformationalVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
